"""google calendar connections and outbox

Revision ID: 8d2b22777103
Revises: 8d9c211a40b2
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8d2b22777103'
down_revision: Union[str, Sequence[str], None] = '8d9c211a40b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_refresh_token', sa.String(length=2048), nullable=False),
    sa.Column('calendar_id', sa.String(length=320), nullable=True),
    sa.Column('calendar_name', sa.String(length=320), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['club_id', 'athlete_id'], ['athletes.club_id', 'athletes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'athlete_id')
    )
    op.create_index(op.f('ix_google_calendar_connections_club_id'), 'google_calendar_connections', ['club_id'], unique=False)
    op.create_table('google_oauth_states',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['club_id', 'athlete_id'], ['athletes.club_id', 'athletes.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('external_calendar_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('google_event_id', sa.String(length=1024), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id', 'assignment_id'], ['assignments.club_id', 'assignments.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['google_calendar_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'assignment_id'),
    sa.UniqueConstraint('connection_id', 'google_event_id')
    )
    op.create_index(op.f('ix_external_calendar_events_club_id'), 'external_calendar_events', ['club_id'], unique=False)
    op.create_index(op.f('ix_external_calendar_events_connection_id'), 'external_calendar_events', ['connection_id'], unique=False)
    op.create_table('google_calendar_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['club_id', 'assignment_id'], ['assignments.club_id', 'assignments.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['google_calendar_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'assignment_id')
    )
    op.create_index(op.f('ix_google_calendar_outbox_club_id'), 'google_calendar_outbox', ['club_id'], unique=False)
    op.create_index(op.f('ix_google_calendar_outbox_connection_id'), 'google_calendar_outbox', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_calendar_outbox_connection_id'), table_name='google_calendar_outbox')
    op.drop_index(op.f('ix_google_calendar_outbox_club_id'), table_name='google_calendar_outbox')
    op.drop_table('google_calendar_outbox')
    op.drop_index(op.f('ix_external_calendar_events_connection_id'), table_name='external_calendar_events')
    op.drop_index(op.f('ix_external_calendar_events_club_id'), table_name='external_calendar_events')
    op.drop_table('external_calendar_events')
    op.drop_table('google_oauth_states')
    op.drop_index(op.f('ix_google_calendar_connections_club_id'), table_name='google_calendar_connections')
    op.drop_table('google_calendar_connections')
    # ### end Alembic commands ###
