"""initial

Revision ID: b5bfc97a50c5
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b5bfc97a50c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'id'),
    sa.UniqueConstraint('club_id', 'user_id')
    )
    op.create_index(op.f('ix_memberships_club_id'), 'memberships', ['club_id'], unique=False)
    op.create_table('athletes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('membership_id', sa.String(length=36), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['club_id', 'membership_id'], ['memberships.club_id', 'memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'id'),
    sa.UniqueConstraint('club_id', 'membership_id')
    )
    op.create_index(op.f('ix_athletes_club_id'), 'athletes', ['club_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('coach_membership_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('training_type', sa.String(length=32), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('prescription', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['club_id', 'coach_membership_id'], ['memberships.club_id', 'memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'id')
    )
    op.create_index(op.f('ix_workout_sessions_club_id'), 'workout_sessions', ['club_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('prescription_snapshot', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id', 'athlete_id'], ['athletes.club_id', 'athletes.id'], ),
    sa.ForeignKeyConstraint(['club_id', 'session_id'], ['workout_sessions.club_id', 'workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'id'),
    sa.UniqueConstraint('club_id', 'session_id', 'athlete_id')
    )
    op.create_index(op.f('ix_assignments_club_id'), 'assignments', ['club_id'], unique=False)
    op.create_table('coach_athlete_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('coach_membership_id', sa.String(length=36), nullable=False),
    sa.Column('athlete_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['club_id', 'athlete_id'], ['athletes.club_id', 'athletes.id'], ),
    sa.ForeignKeyConstraint(['club_id', 'coach_membership_id'], ['memberships.club_id', 'memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'coach_membership_id', 'athlete_id')
    )
    op.create_index(op.f('ix_coach_athlete_grants_club_id'), 'coach_athlete_grants', ['club_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id', 'assignment_id'], ['assignments.club_id', 'assignments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'assignment_id')
    )
    op.create_index(op.f('ix_executions_club_id'), 'executions', ['club_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('feeling', sa.Integer(), nullable=True),
    sa.Column('has_pain', sa.Boolean(), nullable=False),
    sa.Column('pain_area', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['club_id', 'assignment_id'], ['assignments.club_id', 'assignments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'assignment_id')
    )
    op.create_index(op.f('ix_feedback_club_id'), 'feedback', ['club_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_club_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_executions_club_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_coach_athlete_grants_club_id'), table_name='coach_athlete_grants')
    op.drop_table('coach_athlete_grants')
    op.drop_index(op.f('ix_assignments_club_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_workout_sessions_club_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_athletes_club_id'), table_name='athletes')
    op.drop_table('athletes')
    op.drop_index(op.f('ix_memberships_club_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('clubs')
    # ### end Alembic commands ###
